### ISSUE TITLE
Feature request: Server Started

### ISSUE THREAD

**Issue by ChildoftheBeast** [Geek202/server-launcher#1]
Just a small feature request for "Server Started" to be added into the webhook so you can see if your server hung somewhere in the startup and needs user intervention.

Maybe to add on even further, possibly having a user defined timer (or record an average startup time after 3 startups) that sends another message along the lines of "the server may be having trouble starting up and may need user intervention" or simply "the server may have failed to start"

**Comment by Tom-The-Geek** [comment]
This program doesn't have any ability to know the state of the server, and I'm also doing my best to keep it Minecraft independent. If your looking for server starting/stopping messages, I'd suggest you look into a discord bridge mod such as my own: https://github.com/Geek202/TomsServerUtils, or one of the others on this list: https://github.com/comp500/fabric-serverside-mods
